title: Risk-data Library
author:
  name: Global Facility for Disaster Reduction and Recovery
markdown: kramdown

sass:
  # sass_dir: _sass -- default
  style: compressed

collections:
  components:
    order:
      - schema.md
      - dataset.md
      - future-content.md
    output: true
  documentation:
    order:
      - first-documentation.md
      - second-documentation.md
    output: true

google_analytics: 'UA-164674068-1'

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.lock.json
  - package.json
  - webpack.config.babel.js
  - src
