title: Risk Data Library
author:
  name: Global Facility for Disaster Reduction and Recovery
markdown: kramdown

api:
  baseUrl: https://d3utuyt0gg.execute-api.ap-southeast-2.amazonaws.com/dev

sass:
  # sass_dir: _sass -- default
  style: compressed

collections:
  components:
    sort_by: order
    output: true
  documentation:
    permalink: /:collection/:name
    sort_by: order
    output: true

google_analytics: 'UA-164674068-1'
